  name: Deploy to github pages
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-16.04
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  "12.16.3"
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: npm/yarn/pnpm install
          uses: Jaid/action-npm-install@v1.2.4

        - name: Run deploy script
          env:
            USERMAIL: ${{ secrets.USERMAIL }}
          run: |
            git config user.name "Jose Murillo" && git config user.email "$USERMAIL"
            npm run gh-pages-deploy